spring:
  datasource:
    username: root
    password: 123456
    data: classpath:sql/data.sql
    url: jdbc:mysql://localhost:3306/robot_chat?serverTimezone=Asia/Shanghai
    schema: classpath:sql/schema.sql
  session:
    jdbc:
      initialize-schema: always


server:
  port: 8083
